language: rust

rust:
  - stable

cache:
  cargo: true
  directories:
   - $HOME/deps

branches:
  only:
    - staging
    - trying
    - master
  except:
    - staging.tmp

env:
  global:
    - RUSTFLAGS="-C link-dead-code"

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake
            - gcc
            - binutils-dev
            - libiberty-dev
          sources:
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
    - os: osx
      osx_image: xcode9
      compiler: clang
      env:
        - MATRIX_EVAL="export CXX=clang++ && export CC=clang && export MACOSX_DEPLOYMENT_TARGET=10.7"

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - |
      cargo build --verbose --all &&
      cargo test --verbose --all

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c09595dea93d78afd940
    on_success: change
    on_failure: always
    on_start: never

after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  cd kcov-master &&
  mkdir build &&
  cd build &&
  cmake .. &&
  make &&
  make install DESTDIR=../../kcov-build &&
  cd ../.. &&
  rm -rf kcov-master &&
  for file in target/debug/*[^\.d]; do mkdir -p "target/cov/$(basename $file)"; ./kcov-build/usr/local/bin/kcov --include-path=spirv_cross/src --exclude-pattern=/.cargo,/usr/lib,.cpp,.hpp,vendor,tests,bindings.rs --verify "target/cov/$(basename $file)" "$file"; done &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"
