
var sc_internal_wrapper = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  return (
function(sc_internal_wrapper) {
  sc_internal_wrapper = sc_internal_wrapper || {};

var e;e||(e=typeof sc_internal_wrapper !== 'undefined' ? sc_internal_wrapper : {});var h={},l;for(l in e)e.hasOwnProperty(l)&&(h[l]=e[l]);e.arguments=[];e.thisProgram="./this.program";e.quit=function(a,b){throw b;};e.preRun=[];e.postRun=[];var m=!1,n=!1,p=!1,ba=!1;m="object"===typeof window;n="function"===typeof importScripts;p="object"===typeof process&&"function"===typeof require&&!m&&!n;ba=!m&&!p&&!n;var r="";
if(p){r=__dirname+"/";var ca,da;e.read=function(a,b){ca||(ca=require("fs"));da||(da=require("path"));a=da.normalize(a);a=ca.readFileSync(a);return b?a:a.toString()};e.readBinary=function(a){a=e.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(e.thisProgram=process.argv[1].replace(/\\/g,"/"));e.arguments=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof ea))throw a;});process.on("unhandledRejection",u);e.quit=function(a){process.exit(a)};
e.inspect=function(){return"[Emscripten Module object]"}}else if(ba)"undefined"!=typeof read&&(e.read=function(a){return read(a)}),e.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?e.arguments=scriptArgs:"undefined"!=typeof arguments&&(e.arguments=arguments),"function"===typeof quit&&(e.quit=function(a){quit(a)});else if(m||n)n?r=self.location.href:document.currentScript&&
(r=document.currentScript.src),_scriptDir&&(r=_scriptDir),0!==r.indexOf("blob:")?r=r.substr(0,r.lastIndexOf("/")+1):r="",e.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},n&&(e.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),e.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||
0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},e.setWindowTitle=function(a){document.title=a};var fa=e.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),v=e.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||fa);for(l in h)h.hasOwnProperty(l)&&(e[l]=h[l]);h=void 0;var ha={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}};
"object"!==typeof WebAssembly&&v("no native wasm support detected");var x,ia=!1;function assert(a,b){a||u("Assertion failed: "+b)}var ja="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function z(a,b){for(var c=b;a[c];)++c;if(16<c-b&&a.subarray&&ja)return ja.decode(a.subarray(b,c));for(c="";;){var d=a[b++];if(!d)return c;if(d&128){var f=a[b++]&63;if(192==(d&224))c+=String.fromCharCode((d&31)<<6|f);else{var g=a[b++]&63;d=224==(d&240)?(d&15)<<12|f<<6|g:(d&7)<<18|f<<12|g<<6|a[b++]&63;65536>d?c+=String.fromCharCode(d):(d-=65536,c+=String.fromCharCode(55296|d>>10,56320|d&1023))}}else c+=String.fromCharCode(d)}}function A(a){return a?z(B,a):""}
function ka(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var q=a.charCodeAt(++g);k=65536+((k&1023)<<10)|q&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-f}
function la(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function ma(a){0<a%65536&&(a+=65536-a%65536);return a}var buffer,na,B,C,oa;
function pa(){e.HEAP8=na=new Int8Array(buffer);e.HEAP16=new Int16Array(buffer);e.HEAP32=C=new Int32Array(buffer);e.HEAPU8=B=new Uint8Array(buffer);e.HEAPU16=new Uint16Array(buffer);e.HEAPU32=oa=new Uint32Array(buffer);e.HEAPF32=new Float32Array(buffer);e.HEAPF64=new Float64Array(buffer)}var D=e.TOTAL_MEMORY||16777216;5242880>D&&v("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+D+"! (TOTAL_STACK=5242880)");
e.buffer?buffer=e.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(x=new WebAssembly.Memory({initial:D/65536}),buffer=x.buffer):buffer=new ArrayBuffer(D),e.buffer=buffer);pa();C[11612]=5289584;function qa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.Ad;"number"===typeof c?void 0===b.Fa?e.dynCall_v(c):e.dynCall_vi(c,b.Fa):c(void 0===b.Fa?null:b.Fa)}}}var ra=[],sa=[],ta=[],ua=[],va=[],wa=!1;
function xa(){var a=e.preRun.shift();ra.unshift(a)}var E=0,ya=null,F=null;e.preloadedImages={};e.preloadedAudios={};function za(){var a=G;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var G="spirv_cross_wrapper_glsl.wasm";if(!za()){var Aa=G;G=e.locateFile?e.locateFile(Aa,r):r+Aa}
function Ba(){try{if(e.wasmBinary)return new Uint8Array(e.wasmBinary);if(e.readBinary)return e.readBinary(G);throw"both async and sync fetching of the wasm failed";}catch(a){u(a)}}function Ca(){return e.wasmBinary||!m&&!n||"function"!==typeof fetch?new Promise(function(a){a(Ba())}):fetch(G,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+G+"'";return a.arrayBuffer()}).catch(function(){return Ba()})}
function Da(a){function b(a){a=a.exports;if(a.memory){var b=a.memory,c=e.buffer;b.byteLength<c.byteLength&&v("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");c=new Int8Array(c);(new Int8Array(b)).set(c);e.buffer=buffer=b;pa()}e.asm=a;E--;e.monitorRunDependencies&&e.monitorRunDependencies(E);0==E&&(null!==ya&&(clearInterval(ya),ya=null),F&&(a=F,F=null,a()))}function c(a){b(a.instance)}function d(a){Ca().then(function(a){return WebAssembly.instantiate(a,
f)}).then(a,function(a){v("failed to asynchronously prepare wasm: "+a);u(a)})}var f={env:a,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:ha};E++;e.monitorRunDependencies&&e.monitorRunDependencies(E);if(e.instantiateWasm)try{return e.instantiateWasm(f,b)}catch(g){return v("Module.instantiateWasm callback failed with error: "+g),!1}e.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||za()||"function"!==typeof fetch?d(c):WebAssembly.instantiateStreaming(fetch(G,{credentials:"same-origin"}),
f).then(c,function(a){v("wasm streaming compile failed: "+a);v("falling back to ArrayBuffer instantiation");d(c)});return{}}e.asm=function(a,b){b.memory=x;b.table=new WebAssembly.Table({initial:557,maximum:557,element:"anyfunc"});b.__memory_base=1024;b.__table_base=0;return Da(b)};function Ea(a){e.___errno_location&&(C[e.___errno_location()>>2]=a);return a}
function Fa(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function Ga(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Fa(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Ha(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Ia(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function Ja(){var a=Array.prototype.slice.call(arguments,0);return Ga(a.join("/"))}function H(a,b){return Ga(a+"/"+b)}
function Ka(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Fa(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var La=[];function Ma(a,b){La[a]={input:[],output:[],ua:b};Na(a,Oa)}
var Oa={open:function(a){var b=La[a.node.rdev];if(!b)throw new I(J.Ea);a.tty=b;a.seekable=!1},close:function(a){a.tty.ua.flush(a.tty)},flush:function(a){a.tty.ua.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.ua.Va)throw new I(J.Ma);for(var f=0,g=0;g<d;g++){try{var k=a.tty.ua.Va(a.tty)}catch(q){throw new I(J.Ka);}if(void 0===k&&0===f)throw new I(J.Za);if(null===k||void 0===k)break;f++;b[c+g]=k}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.ua.Ia)throw new I(J.Ma);
try{for(var f=0;f<d;f++)a.tty.ua.Ia(a.tty,b[c+f])}catch(g){throw new I(J.Ka);}d&&(a.node.timestamp=Date.now());return f}},Qa={Va:function(a){if(!a.input.length){var b=null;if(p){var c=new Buffer(256),d=0,f=process.stdin.fd;if("win32"!=process.platform){var g=!1;try{f=fs.openSync("/dev/stdin","r"),g=!0}catch(k){}}try{d=fs.readSync(f,c,0,256,null)}catch(k){if(-1!=k.toString().indexOf("EOF"))d=0;else throw k;}g&&fs.closeSync(f);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Pa(b,!0)}return a.input.shift()},Ia:function(a,b){null===b||10===b?(fa(z(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(fa(z(a.output,0)),a.output=[])}},Ra={Ia:function(a,b){null===b||10===b?(v(z(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&
(v(z(a.output,0)),a.output=[])}},K={ma:null,ia:function(){return K.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new I(J.cb);K.ma||(K.ma={dir:{node:{na:K.ea.na,ka:K.ea.ka,lookup:K.ea.lookup,wa:K.ea.wa,rename:K.ea.rename,unlink:K.ea.unlink,rmdir:K.ea.rmdir,readdir:K.ea.readdir,symlink:K.ea.symlink},stream:{oa:K.fa.oa}},file:{node:{na:K.ea.na,ka:K.ea.ka},stream:{oa:K.fa.oa,read:K.fa.read,write:K.fa.write,Na:K.fa.Na,Wa:K.fa.Wa,Ba:K.fa.Ba}},link:{node:{na:K.ea.na,
ka:K.ea.ka,readlink:K.ea.readlink},stream:{}},Pa:{node:{na:K.ea.na,ka:K.ea.ka},stream:Sa}});c=Ta(a,b,c,d);16384===(c.mode&61440)?(c.ea=K.ma.dir.node,c.fa=K.ma.dir.stream,c.da={}):32768===(c.mode&61440)?(c.ea=K.ma.file.node,c.fa=K.ma.file.stream,c.ga=0,c.da=null):40960===(c.mode&61440)?(c.ea=K.ma.link.node,c.fa=K.ma.link.stream):8192===(c.mode&61440)&&(c.ea=K.ma.Pa.node,c.fa=K.ma.Pa.stream);c.timestamp=Date.now();a&&(a.da[b]=c);return c},Bd:function(a){if(a.da&&a.da.subarray){for(var b=[],c=0;c<a.ga;++c)b.push(a.da[c]);
return b}return a.da},Cd:function(a){return a.da?a.da.subarray?a.da.subarray(0,a.ga):new Uint8Array(a.da):new Uint8Array},Qa:function(a,b){var c=a.da?a.da.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.da,a.da=new Uint8Array(b),0<a.ga&&a.da.set(c.subarray(0,a.ga),0))},kb:function(a,b){if(a.ga!=b)if(0==b)a.da=null,a.ga=0;else{if(!a.da||a.da.subarray){var c=a.da;a.da=new Uint8Array(new ArrayBuffer(b));c&&a.da.set(c.subarray(0,Math.min(b,a.ga)))}else if(a.da||(a.da=
[]),a.da.length>b)a.da.length=b;else for(;a.da.length<b;)a.da.push(0);a.ga=b}},ea:{na:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.ga:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.qa=4096;b.blocks=Math.ceil(b.size/b.qa);return b},ka:function(a,b){void 0!==b.mode&&
(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&K.kb(a,b.size)},lookup:function(){throw Ua[J.ab];},wa:function(a,b,c,d){return K.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=Va(b,c)}catch(g){}if(d)for(var f in d.da)throw new I(J.La);}delete a.parent.da[a.name];a.name=c;b.da[c]=a;a.parent=b},unlink:function(a,b){delete a.da[b]},rmdir:function(a,b){var c=Va(a,b),d;for(d in c.da)throw new I(J.La);delete a.da[b]},readdir:function(a){var b=
[".",".."],c;for(c in a.da)a.da.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=K.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new I(J.sa);return a.link}},fa:{read:function(a,b,c,d,f){var g=a.node.da;if(f>=a.node.ga)return 0;a=Math.min(a.node.ga-f,d);assert(0<=a);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){g=!1;if(!d)return 0;a=a.node;a.timestamp=Date.now();
if(b.subarray&&(!a.da||a.da.subarray)){if(g)return a.da=b.subarray(c,c+d),a.ga=d;if(0===a.ga&&0===f)return a.da=new Uint8Array(b.subarray(c,c+d)),a.ga=d;if(f+d<=a.ga)return a.da.set(b.subarray(c,c+d),f),d}K.Qa(a,f+d);if(a.da.subarray&&b.subarray)a.da.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.da[f+g]=b[c+g];a.ga=Math.max(a.ga,f+d);return d},oa:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ga);if(0>b)throw new I(J.sa);return b},Na:function(a,b,c){K.Qa(a.node,
b+c);a.node.ga=Math.max(a.node.ga,b+c)},Wa:function(a,b,c,d,f,g,k){if(32768!==(a.node.mode&61440))throw new I(J.Ea);c=a.node.da;if(k&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<f||f+d<a.node.ga)c.subarray?c=c.subarray(f,f+d):c=Array.prototype.slice.call(c,f,f+d);a=!0;d=Wa(d);if(!d)throw new I(J.bb);b.set(c,d)}else a=!1,d=c.byteOffset;return{Fd:d,eb:a}},Ba:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new I(J.Ea);if(f&2)return 0;K.fa.write(a,b,0,d,c,!1);return 0}}},L={za:!1,mb:function(){L.za=
!!process.platform.match(/^win/);var a=process.binding("constants");a.fs&&(a=a.fs);L.Ra={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},Oa:function(a){return Buffer.la?Buffer.from(a):new Buffer(a)},ia:function(a){assert(p);return L.createNode(null,"/",L.Ua(a.Ha.root),0)},createNode:function(a,b,c){if(16384!==(c&61440)&&32768!==(c&61440)&&40960!==(c&61440))throw new I(J.sa);a=Ta(a,b,c);a.ea=L.ea;a.fa=L.fa;return a},Ua:function(a){try{var b=
fs.lstatSync(a);L.za&&(b.mode=b.mode|(b.mode&292)>>2)}catch(c){if(!c.code)throw c;throw new I(J[c.code]);}return b.mode},ja:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.ia.Ha.root);b.reverse();return Ja.apply(null,b)},gb:function(a){a&=-2656257;var b=0,c;for(c in L.Ra)a&c&&(b|=L.Ra[c],a^=c);if(a)throw new I(J.sa);return b},ea:{na:function(a){a=L.ja(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new I(J[c.code]);}L.za&&!b.qa&&(b.qa=4096);L.za&&!b.blocks&&
(b.blocks=(b.size+b.qa-1)/b.qa|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,qa:b.qa,blocks:b.blocks}},ka:function(a,b){var c=L.ja(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new I(J[d.code]);}},lookup:function(a,b){var c=H(L.ja(a),b);c=L.Ua(c);return L.createNode(a,b,c)},wa:function(a,b,c,d){a=L.createNode(a,
b,c,d);b=L.ja(a);try{16384===(a.mode&61440)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(f){if(!f.code)throw f;throw new I(J[f.code]);}return a},rename:function(a,b,c){a=L.ja(a);b=H(L.ja(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new I(J[d.code]);}},unlink:function(a,b){a=H(L.ja(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new I(J[c.code]);}},rmdir:function(a,b){a=H(L.ja(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new I(J[c.code]);
}},readdir:function(a){a=L.ja(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new I(J[b.code]);}},symlink:function(a,b,c){a=H(L.ja(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new I(J[d.code]);}},readlink:function(a){var b=L.ja(a);try{return b=fs.readlinkSync(b),b=Xa.relative(Xa.resolve(a.ia.Ha.root),b)}catch(c){if(!c.code)throw c;throw new I(J[c.code]);}}},fa:{open:function(a){var b=L.ja(a.node);try{32768===(a.node.mode&61440)&&(a.ya=fs.openSync(b,L.gb(a.flags)))}catch(c){if(!c.code)throw c;
throw new I(J[c.code]);}},close:function(a){try{32768===(a.node.mode&61440)&&a.ya&&fs.closeSync(a.ya)}catch(b){if(!b.code)throw b;throw new I(J[b.code]);}},read:function(a,b,c,d,f){if(0===d)return 0;try{return fs.readSync(a.ya,L.Oa(b.buffer),c,d,f)}catch(g){throw new I(J[g.code]);}},write:function(a,b,c,d,f){try{return fs.writeSync(a.ya,L.Oa(b.buffer),c,d,f)}catch(g){throw new I(J[g.code]);}},oa:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.ya).size}catch(d){throw new I(J[d.code]);
}if(0>b)throw new I(J.sa);return b}}},Ya=null,Za={},N=[],$a=1,O=null,ab=!0,bb={},I=null,Ua={};
function P(a,b){a=Ka("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Ta:!0,Ja:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Ja)throw new I(40);a=Fa(a.split("/").filter(function(a){return!!a}),!1);var f=Ya;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=Va(f,a[d]);c=H(c,a[d]);f.Aa&&(!g||g&&b.Ta)&&(f=f.Aa.root);if(!g||b.Sa)for(g=0;40960===(f.mode&61440);)if(f=cb(c),c=Ka(Ha(c),f),f=P(c,{Ja:b.Ja}).node,40<g++)throw new I(40);}return{path:c,node:f}}
function db(a){for(var b;;){if(a===a.parent)return a=a.ia.Xa,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function eb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%O.length}function fb(a){var b=eb(a.parent.id,a.name);a.jb=O[b];O[b]=a}function Va(a,b){var c;if(c=(c=gb(a,"x"))?c:a.ea.lookup?0:13)throw new I(c,a);for(c=O[eb(a.id,b)];c;c=c.jb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.ea.lookup(a,b)}
function Ta(a,b,c,d){Q||(Q=function(a,b,c,d){a||(a=this);this.parent=a;this.ia=a.ia;this.Aa=null;this.id=$a++;this.name=b;this.mode=c;this.ea={};this.fa={};this.rdev=d},Q.prototype={},Object.defineProperties(Q.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}}));a=new Q(a,b,c,d);fb(a);return a}
var hb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function ib(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function gb(a,b){if(ab)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 13}else return 13;return 0}function jb(a,b){try{return Va(a,b),17}catch(c){}return gb(a,"wx")}
function kb(){var a=4096;for(var b=0;b<=a;b++)if(!N[b])return b;throw new I(24);}function lb(a){R||(R=function(){},R.prototype={},Object.defineProperties(R.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var b=new R,c;for(c in a)b[c]=a[c];a=b;b=kb();a.fd=b;return N[b]=a}var Sa={open:function(a){a.fa=Za[a.node.rdev].fa;a.fa.open&&a.fa.open(a)},oa:function(){throw new I(29);}};function Na(a,b){Za[a]={fa:b}}
function mb(a,b){var c="/"===b,d=!b;if(c&&Ya)throw new I(16);if(!c&&!d){var f=P(b,{Ta:!1});b=f.path;f=f.node;if(f.Aa)throw new I(16);if(16384!==(f.mode&61440))throw new I(20);}b={type:a,Ha:{},Xa:b,ib:[]};a=a.ia(b);a.ia=b;b.root=a;c?Ya=a:f&&(f.Aa=b,f.ia&&f.ia.ib.push(b))}function nb(a,b,c){var d=P(a,{parent:!0}).node;a=Ia(a);if(!a||"."===a||".."===a)throw new I(22);var f=jb(d,a);if(f)throw new I(f);if(!d.ea.wa)throw new I(1);return d.ea.wa(d,a,b,c)}function S(a){nb(a,16895,0)}
function ob(a,b,c){"undefined"===typeof c&&(c=b,b=438);nb(a,b|8192,c)}function pb(a,b){if(!Ka(a))throw new I(2);var c=P(b,{parent:!0}).node;if(!c)throw new I(2);b=Ia(b);var d=jb(c,b);if(d)throw new I(d);if(!c.ea.symlink)throw new I(1);c.ea.symlink(c,b,a)}function cb(a){a=P(a).node;if(!a)throw new I(2);if(!a.ea.readlink)throw new I(22);return Ka(db(a.parent),a.ea.readlink(a))}
function qb(a,b){if(""===a)throw new I(2);if("string"===typeof b){var c=hb[b];if("undefined"===typeof c)throw Error("Unknown file open mode: "+b);b=c}var d=b&64?("undefined"===typeof d?438:d)&4095|32768:0;if("object"===typeof a)var f=a;else{a=Ga(a);try{f=P(a,{Sa:!(b&131072)}).node}catch(k){}}c=!1;if(b&64)if(f){if(b&128)throw new I(17);}else f=nb(a,d,0),c=!0;if(!f)throw new I(2);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new I(20);if(!c&&(d=f?40960===(f.mode&61440)?40:
16384===(f.mode&61440)&&("r"!==ib(b)||b&512)?21:gb(f,ib(b)):2))throw new I(d);if(b&512){d=f;var g;"string"===typeof d?g=P(d,{Sa:!0}).node:g=d;if(!g.ea.ka)throw new I(1);if(16384===(g.mode&61440))throw new I(21);if(32768!==(g.mode&61440))throw new I(22);if(d=gb(g,"w"))throw new I(d);g.ea.ka(g,{size:0,timestamp:Date.now()})}b&=-641;f=lb({node:f,path:db(f),flags:b,seekable:!0,position:0,fa:f.fa,rb:[],error:!1});f.fa.open&&f.fa.open(f);!e.logReadFiles||b&1||(sb||(sb={}),a in sb||(sb[a]=1,console.log("FS.trackingDelegate error on read file: "+
a)));try{bb.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),bb.onOpenFile(a,g))}catch(k){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+k.message)}return f}function tb(a){if(null===a.fd)throw new I(9);a.Ga&&(a.Ga=null);try{a.fa.close&&a.fa.close(a)}catch(b){throw b;}finally{N[a.fd]=null}a.fd=null}
function ub(a,b,c){if(null===a.fd)throw new I(9);if(!a.seekable||!a.fa.oa)throw new I(29);if(0!=c&&1!=c&&2!=c)throw new I(22);a.position=a.fa.oa(a,b,c);a.rb=[]}function vb(){I||(I=function(a,b){this.node=b;this.lb=function(a){this.va=a};this.lb(a);this.message="FS error";this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0})},I.prototype=Error(),I.prototype.constructor=I,[2].forEach(function(a){Ua[a]=new I(a);Ua[a].stack="<generic error, no stack>"}))}var wb;
function xb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function T(a,b,c){a=H("/dev",a);var d=xb(!!b,!!c);yb||(yb=64);var f=yb++<<8|0;Na(f,{open:function(a){a.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(a,c,d,f){for(var g=0,k=0;k<f;k++){try{var q=b()}catch(M){throw new I(5);}if(void 0===q&&0===g)throw new I(11);if(null===q||void 0===q)break;g++;c[d+k]=q}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,d,f){for(var g=0;g<f;g++)try{c(b[d+g])}catch(t){throw new I(5);}f&&(a.node.timestamp=Date.now());return g}});
ob(a,d,f)}
var yb,U={},Q,R,sb,J={cb:1,ab:2,md:3,bc:4,Ka:5,Ma:6,sb:7,Dc:8,$a:9,Ib:10,Za:11,wd:11,bb:12,tb:13,Vb:14,Pc:15,Gb:16,Ub:17,xd:18,Ea:19,Rc:20,dc:21,sa:22,yc:23,qc:24,ta:25,td:26,Wb:27,Lc:28,ld:29,hd:30,rc:31,$c:32,Rb:33,dd:34,Hc:42,Zb:43,Jb:44,fc:45,hc:46,ic:47,oc:48,ud:49,Bc:50,ec:51,Ob:35,Ec:37,zb:52,Cb:53,yd:54,zc:55,Db:56,Eb:57,Pb:35,Fb:59,Nc:60,Cc:61,qd:62,Mc:63,Ic:64,Jc:65,gd:66,Fc:67,wb:68,nd:69,Kb:70,ad:71,tc:72,Sb:73,Bb:74,Vc:76,Ab:77,ed:78,jc:79,kc:80,nc:81,mc:82,lc:83,Oc:38,La:39,uc:36,pc:40,
Wc:95,Zc:96,Nb:104,Ac:105,xb:97,cd:91,Tc:88,Kc:92,jd:108,Mb:111,ub:98,Lb:103,xc:101,vc:100,rd:110,Xb:112,Yb:113,ac:115,yb:114,Qb:89,sc:90,bd:93,kd:94,vb:99,wc:102,cc:106,Qc:107,sd:109,vd:87,Tb:122,od:116,Uc:95,Gc:123,$b:84,Xc:75,Hb:125,Sc:131,Yc:130,pd:86},zb={},V=0;function W(){V+=4;return C[V-4>>2]}function Ab(){var a=N[W()];if(!a)throw new I(J.$a);return a}var Bb={};
function Y(a){if(0===a)return 0;a=A(a);if(!Bb.hasOwnProperty(a))return 0;Y.la&&Cb(Y.la);a=Bb[a];var b=la(a)+1,c=Wa(b);c&&ka(a,na,c,b);Y.la=c;return Y.la}function Z(){Z.la||(Z.la=[]);Z.la.push(Db());return Z.la.length-1}function Eb(a){return 0===a%4&&(0!==a%100||0===a%400)}function Fb(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Gb=[31,29,31,30,31,30,31,31,30,31,30,31],Hb=[31,28,31,30,31,30,31,31,30,31,30,31];
function Ib(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Eb(a.getFullYear())?Gb:Hb)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Jb(a,b,c,d){function f(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function g(a,b){return f(a,b,"0")}function k(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=c(a.getFullYear()-b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function q(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),
0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function w(a){a=Ib(new Date(a.ha+1900,0,1),a.Da);var b=q(new Date(a.getFullYear()+1,0,4));return 0>=k(q(new Date(a.getFullYear(),0,4)),a)?0>=k(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var y=C[d+40>>2];d={pb:C[d>>2],ob:C[d+4>>2],Ca:C[d+8>>2],ra:C[d+12>>2],pa:C[d+16>>2],ha:C[d+20>>2],Ya:C[d+24>>2],Da:C[d+28>>2],Gd:C[d+32>>2],nb:C[d+36>>2],
qb:y?A(y):""};c=A(c);y={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S"};for(var t in y)c=c.replace(new RegExp(t,"g"),y[t]);var X="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),M="January February March April May June July August September October November December".split(" ");y={"%a":function(a){return X[a.Ya].substring(0,3)},"%A":function(a){return X[a.Ya]},"%b":function(a){return M[a.pa].substring(0,
3)},"%B":function(a){return M[a.pa]},"%C":function(a){return g((a.ha+1900)/100|0,2)},"%d":function(a){return g(a.ra,2)},"%e":function(a){return f(a.ra,2," ")},"%g":function(a){return w(a).toString().substring(2)},"%G":function(a){return w(a)},"%H":function(a){return g(a.Ca,2)},"%I":function(a){a=a.Ca;0==a?a=12:12<a&&(a-=12);return g(a,2)},"%j":function(a){return g(a.ra+Fb(Eb(a.ha+1900)?Gb:Hb,a.pa-1),3)},"%m":function(a){return g(a.pa+1,2)},"%M":function(a){return g(a.ob,2)},"%n":function(){return"\n"},
"%p":function(a){return 0<=a.Ca&&12>a.Ca?"AM":"PM"},"%S":function(a){return g(a.pb,2)},"%t":function(){return"\t"},"%u":function(a){return(new Date(a.ha+1900,a.pa+1,a.ra,0,0,0,0)).getDay()||7},"%U":function(a){var b=new Date(a.ha+1900,0,1),c=0===b.getDay()?b:Ib(b,7-b.getDay());a=new Date(a.ha+1900,a.pa,a.ra);return 0>k(c,a)?g(Math.ceil((31-c.getDate()+(Fb(Eb(a.getFullYear())?Gb:Hb,a.getMonth()-1)-31)+a.getDate())/7),2):0===k(c,b)?"01":"00"},"%V":function(a){var b=q(new Date(a.ha+1900,0,4)),c=q(new Date(a.ha+
1901,0,4)),d=Ib(new Date(a.ha+1900,0,1),a.Da);return 0>k(d,b)?"53":0>=k(c,d)?"01":g(Math.ceil((b.getFullYear()<a.ha+1900?a.Da+32-b.getDate():a.Da+1-b.getDate())/7),2)},"%w":function(a){return(new Date(a.ha+1900,a.pa+1,a.ra,0,0,0,0)).getDay()},"%W":function(a){var b=new Date(a.ha,0,1),c=1===b.getDay()?b:Ib(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.ha+1900,a.pa,a.ra);return 0>k(c,a)?g(Math.ceil((31-c.getDate()+(Fb(Eb(a.getFullYear())?Gb:Hb,a.getMonth()-1)-31)+a.getDate())/7),2):0===k(c,b)?"01":
"00"},"%y":function(a){return(a.ha+1900).toString().substring(2)},"%Y":function(a){return a.ha+1900},"%z":function(a){a=a.nb;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.qb},"%%":function(){return"%"}};for(t in y)0<=c.indexOf(t)&&(c=c.replace(new RegExp(t,"g"),y[t](d)));t=Pa(c,!1);if(t.length>b)return 0;na.set(t,a);return t.length-1}vb();O=Array(4096);mb(K,"/");S("/tmp");S("/home");S("/home/web_user");
(function(){S("/dev");Na(259,{read:function(){return 0},write:function(a,b,c,k){return k}});ob("/dev/null",259);Ma(1280,Qa);Ma(1536,Ra);ob("/dev/tty",1280);ob("/dev/tty1",1536);if("object"===typeof c&&"function"===typeof c.getRandomValues){var a=new Uint8Array(1);var b=function(){c.getRandomValues(a);return a[0]}}else if(p)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){b=function(){return 256*Math.random()|0}}else b=function(){u("random_device")};T("random",b);T("urandom",
b);S("/dev/shm");S("/dev/shm/tmp")})();S("/proc");S("/proc/self");S("/proc/self/fd");mb({ia:function(){var a=Ta("/proc/self","fd",16895,73);a.ea={lookup:function(a,c){var b=N[+c];if(!b)throw new I(9);a={parent:null,ia:{Xa:"fake"},ea:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");
sa.unshift(function(){if(!e.noFSInit&&!wb){assert(!wb,"FS.init was previously called. If you want to initialize later with custom parameters, remove any earlier calls (note that one is automatically added to the generated code)");wb=!0;vb();e.stdin=e.stdin;e.stdout=e.stdout;e.stderr=e.stderr;e.stdin?T("stdin",e.stdin):pb("/dev/tty","/dev/stdin");e.stdout?T("stdout",null,e.stdout):pb("/dev/tty","/dev/stdout");e.stderr?T("stderr",null,e.stderr):pb("/dev/tty1","/dev/stderr");var a=qb("/dev/stdin","r");
assert(0===a.fd,"invalid handle for stdin ("+a.fd+")");a=qb("/dev/stdout","w");assert(1===a.fd,"invalid handle for stdout ("+a.fd+")");a=qb("/dev/stderr","w");assert(2===a.fd,"invalid handle for stderr ("+a.fd+")")}});ta.push(function(){ab=!1});ua.push(function(){wb=!1;var a=e._fflush;a&&a(0);for(a=0;a<N.length;a++){var b=N[a];b&&tb(b)}});sa.unshift(function(){});ua.push(function(){});if(p){var fs=require("fs"),Xa=require("path");L.mb()}
function Pa(a,b){var c=Array(la(a)+1);a=ka(a,c,0,c.length);b&&(c.length=a);return c}
e.fb={d:u,c:function(a,b,c,d){u("Assertion failed: "+A(a)+", at: "+[b?A(b):"unknown filename",c,d?A(d):"unknown function"])},r:function(){return!!Kb.zd},i:function(){},o:function(){Ea(1);return-1},k:Ea,n:function(a,b){V=b;try{var c=Ab();W();var d=W(),f=W(),g=W();ub(c,d,g);C[f>>2]=c.position;c.Ga&&0===d&&0===g&&(c.Ga=null);return 0}catch(k){return"undefined"!==typeof U&&k instanceof I||u(k),-k.va}},j:function(a,b){V=b;try{var c=Ab(),d=W();a:{var f=W();for(b=a=0;b<f;b++){var g=c,k=C[d+8*b>>2],q=C[d+
(8*b+4)>>2],w=void 0,y=na;if(0>q||0>w)throw new I(22);if(null===g.fd)throw new I(9);if(0===(g.flags&2097155))throw new I(9);if(16384===(g.node.mode&61440))throw new I(21);if(!g.fa.write)throw new I(22);g.flags&1024&&ub(g,0,2);var t="undefined"!==typeof w;if(!t)w=g.position;else if(!g.seekable)throw new I(29);var X=g.fa.write(g,y,k,q,w,void 0);t||(g.position+=X);try{if(g.path&&bb.onWriteToFile)bb.onWriteToFile(g.path)}catch(aa){console.log("FS.trackingDelegate['onWriteToFile']('"+path+"') threw an exception: "+
aa.message)}var M=X;if(0>M){var rb=-1;break a}a+=M}rb=a}return rb}catch(aa){return"undefined"!==typeof U&&aa instanceof I||u(aa),-aa.va}},m:function(a,b){V=b;try{var c=Ab(),d=W();switch(d){case 21509:case 21505:return c.tty?0:-J.ta;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?0:-J.ta;case 21519:if(!c.tty)return-J.ta;var f=W();return C[f>>2]=0;case 21520:return c.tty?-J.sa:-J.ta;case 21531:a=f=W();if(!c.fa.hb)throw new I(25);return c.fa.hb(c,d,a);case 21523:return c.tty?
0:-J.ta;case 21524:return c.tty?0:-J.ta;default:u("bad ioctl syscall "+d)}}catch(g){return"undefined"!==typeof U&&g instanceof I||u(g),-g.va}},l:function(a,b){V=b;try{var c=Ab();tb(c);return 0}catch(d){return"undefined"!==typeof U&&d instanceof I||u(d),-d.va}},w:function(a,b){V=b;try{var c=W(),d=W(),f=zb[c];if(!f)return 0;if(d===f.Dd){var g=N[f.fd],k=f.flags,q=new Uint8Array(B.subarray(c,c+d));g&&g.fa.Ba&&g.fa.Ba(g,q,0,d,k);zb[c]=null;f.eb&&Cb(f.Ed)}return 0}catch(w){return"undefined"!==typeof U&&
w instanceof I||u(w),-w.va}},h:function(){},b:function(){e.abort()},v:function(){return D},u:function(a,b,c){B.set(B.subarray(b,b+c),a)},t:function(a){if(2147418112<a)return!1;for(var b=Math.max(D,16777216);b<a;)536870912>=b?b=ma(2*b):b=Math.min(ma((3*b+2147483648)/4),2147418112);var c=ma(b);var d=e.buffer.byteLength;try{var f=-1!==x.grow((c-d)/65536)?e.buffer=x.buffer:null}catch(g){f=null}if(!f||f.byteLength!=b)return!1;e.buffer=buffer=f;pa();D=b;oa[11612]=a;return!0},g:Y,f:function(a){var b=Z.la[a];
Z.la.splice(a,1);Lb(b)},e:Z,s:function(){return 0},q:function(a,b,c,d){return Jb(a,b,c,d)},p:function(a){u("Cannot enlarge memory arrays to size "+a+" bytes. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+D+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")},a:46448};var Mb=e.asm({},e.fb,buffer);e.asm=Mb;
var Kb=e.__ZSt18uncaught_exceptionv=function(){return e.asm.x.apply(null,arguments)};e.___errno_location=function(){return e.asm.y.apply(null,arguments)};var Cb=e._free=function(){return e.asm.z.apply(null,arguments)},Wa=e._malloc=function(){return e.asm.A.apply(null,arguments)};e._sc_internal_compiler_compile=function(){return e.asm.B.apply(null,arguments)};e._sc_internal_compiler_delete=function(){return e.asm.C.apply(null,arguments)};
e._sc_internal_compiler_get_cleansed_entry_point_name=function(){return e.asm.D.apply(null,arguments)};e._sc_internal_compiler_get_declared_struct_member_size=function(){return e.asm.E.apply(null,arguments)};e._sc_internal_compiler_get_declared_struct_size=function(){return e.asm.F.apply(null,arguments)};e._sc_internal_compiler_get_decoration=function(){return e.asm.G.apply(null,arguments)};e._sc_internal_compiler_get_entry_points=function(){return e.asm.H.apply(null,arguments)};
e._sc_internal_compiler_get_member_decoration=function(){return e.asm.I.apply(null,arguments)};e._sc_internal_compiler_get_member_name=function(){return e.asm.J.apply(null,arguments)};e._sc_internal_compiler_get_shader_resources=function(){return e.asm.K.apply(null,arguments)};e._sc_internal_compiler_get_specialization_constants=function(){return e.asm.L.apply(null,arguments)};e._sc_internal_compiler_get_type=function(){return e.asm.M.apply(null,arguments)};
e._sc_internal_compiler_get_work_group_size_specialization_constants=function(){return e.asm.N.apply(null,arguments)};e._sc_internal_compiler_glsl_build_combined_image_samplers=function(){return e.asm.O.apply(null,arguments)};e._sc_internal_compiler_glsl_get_combined_image_samplers=function(){return e.asm.P.apply(null,arguments)};e._sc_internal_compiler_glsl_new=function(){return e.asm.Q.apply(null,arguments)};e._sc_internal_compiler_glsl_set_options=function(){return e.asm.R.apply(null,arguments)};
e._sc_internal_compiler_rename_interface_variable=function(){return e.asm.S.apply(null,arguments)};e._sc_internal_compiler_set_decoration=function(){return e.asm.T.apply(null,arguments)};e._sc_internal_compiler_set_member_decoration=function(){return e.asm.U.apply(null,arguments)};e._sc_internal_compiler_set_name=function(){return e.asm.V.apply(null,arguments)};e._sc_internal_compiler_set_scalar_constant=function(){return e.asm.W.apply(null,arguments)};
e._sc_internal_compiler_unset_decoration=function(){return e.asm.X.apply(null,arguments)};e._sc_internal_free_pointer=function(){return e.asm.Y.apply(null,arguments)};e._sc_internal_get_latest_exception_message=function(){return e.asm.Z.apply(null,arguments)};var Lb=e.stackRestore=function(){return e.asm.aa.apply(null,arguments)},Db=e.stackSave=function(){return e.asm.ba.apply(null,arguments)};e.dynCall_v=function(){return e.asm._.apply(null,arguments)};
e.dynCall_vi=function(){return e.asm.$.apply(null,arguments)};e.asm=Mb;e.then=function(a){if(e.calledRun)a(e);else{var b=e.onRuntimeInitialized;e.onRuntimeInitialized=function(){b&&b();a(e)}}return e};function ea(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}ea.prototype=Error();ea.prototype.constructor=ea;F=function Nb(){e.calledRun||Ob();e.calledRun||(F=Nb)};
function Ob(){function a(){if(!e.calledRun&&(e.calledRun=!0,!ia)){wa||(wa=!0,qa(sa));qa(ta);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var a=e.postRun.shift();va.unshift(a)}qa(va)}}if(!(0<E)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)xa();qa(ra);0<E||e.calledRun||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},
1);a()},1)):a())}}e.run=Ob;function u(a){if(e.onAbort)e.onAbort(a);void 0!==a?(fa(a),v(a),a=JSON.stringify(a)):a="";ia=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}e.abort=u;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();e.noExitRuntime=!0;Ob();


  return sc_internal_wrapper;
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = sc_internal_wrapper;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return sc_internal_wrapper; });
    else if (typeof exports === 'object')
      exports["sc_internal_wrapper"] = sc_internal_wrapper;
    